all_sections_path = "result/all_sections.json"
model_path = "result/model.bin"
notes_ngrams_path = "result/notes_ngrams.json"
queries_path = "result/queries.json"
results_zip="result/results.zip"
resulst_dir="result"